version: '3'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - "backend/.env"
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
